package monopolinho.tipos;

public enum TipoAccion {
    COMPRAR,
    VENDER,
    HIPOTECAR,
    DESHIPOTECAR,
    EDIFICAR,
    VENDER_EDIFICIOS,
    RECIBIR_PREMIO,
    PAGAR_XOGADORES,
    PAGAR_IMPOSTO,
    PAGAR_ALQUILER,
    IR_CARCEL,
    PAGAR_CARTA,
    LANZAR_DADOS,
    MOVERSE
}
